### PR TITLE
Allow normal users to view all calls

### PR DESCRIPTION
**Pull request by 7h0ma5**
Allow normal users to view all calls

Open for discussion...

### CODE REVIEW

**Comment by dk7td** [comment]
That's ok for me. I don't see a big impact on privacy because the number of direct calls is much less than automated calls from different sources.
Also HAM radio is open communication per definition.

**Comment by phl0** [comment]
No issues for me.

**Comment by dg9vh** [comment]
Also no issue for me :-)

**Comment by josch0** [comment]
Compiliert das fehlerfrei? Du nimmst die Variable „status“ weg, die in den Zeilen weiter unten genutzt wird, oder?

**Comment by Taronyu** [comment]
No issue for me either. Although I see the potential privacy aspect, we should keep in mind that a) ham radio must be readable by anybody and b) if you operate a transmitter in dl-all there is a good chance that you can potentially see a lot of calls anyway. So having the check does not really add to privacy. If no one disagrees, I will perform the merge later.

**Comment by dj7lc** [comment]
All right, do it :-)
I will update the servers once it is merged.

**Comment by Taronyu** [comment]
Changes included in version 1.5.5.6. Note that simply copying over to an existing installation might fail, because the jgroups configuration file has changed in Version >= 4.0.0. I had to update due to a severe security vulnerability. I don't have a fixed example config file yet.

**Pull request merged**
